<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Daily Sales Report</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0; padding:0; background-color:#f5f7fa; font-family: Arial, Helvetica, sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f7fa; padding:24px;">
    <tr>
        <td align="center">

            <!-- Container -->
            <table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:6px; overflow:hidden;">

                <!-- Header -->
                <tr>
                    <td style="background-color:#0d6efd; padding:20px; color:#ffffff;">
                        <h1 style="margin:0; font-size:20px;">Daily Sales Report</h1>
                        <p style="margin:4px 0 0; font-size:13px;">
                            {{ now()->format('F j, Y') }}
                        </p>
                    </td>
                </tr>

                <!-- Content -->
                <tr>
                    <td style="padding:24px; color:#333333;">

                        <p style="margin:0 0 16px;">
                            Hello Admin,
                        </p>

                        <p style="margin:0 0 24px;">
                            Below is the sales summary for today.
                        </p>

                        <!-- Sales Table -->
                        <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;">

                            <tr style="background-color:#f1f3f5;">
                                <th align="left" style="padding:10px; font-size:12px; text-transform:uppercase; color:#555;">
                                    Product
                                </th>
                                <th align="right" style="padding:10px; font-size:12px; text-transform:uppercase; color:#555;">
                                    Quantity Sold
                                </th>
                                <th align="right" style="padding:10px; font-size:12px; text-transform:uppercase; color:#555;">
                                    Revenue
                                </th>
                            </tr>

                            @forelse ($report as $sale)
                                <tr>
                                    <td style="padding:10px; border-bottom:1px solid #e9ecef;">
                                        {{ $sale['name'] }}
                                    </td>
                                    <td align="right" style="padding:10px; border-bottom:1px solid #e9ecef;">
                                        {{ $sale['quantity_sold'] }}
                                    </td>
                                    <td align="right" style="padding:10px; border-bottom:1px solid #e9ecef;">
                                        ${{ number_format($sale['revenue'], 2) }}
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3" align="center" style="padding:20px; color:#777;">
                                        No sales recorded today.
                                    </td>
                                </tr>
                            @endforelse

                            @if(count($report) > 0)
                                <tr style="background-color:#f8f9fa; font-weight:bold;">
                                    <td style="padding:10px;">
                                        Total
                                    </td>
                                    <td align="right" style="padding:10px;">
                                        {{ collect($report)->sum('quantity_sold') }}
                                    </td>
                                    <td align="right" style="padding:10px;">
                                        ${{ number_format(collect($report)->sum('revenue'), 2) }}
                                    </td>
                                </tr>
                            @endif

                        </table>

                        <p style="margin:24px 0 0; font-size:13px;">
                            This is an automated report generated by SwiftCart.
                        </p>

                    </td>
                </tr>

                <!-- Footer -->
                <tr>
                    <td align="center" style="padding:16px; font-size:12px; color:#777777; background-color:#fafafa;">
                        © {{ date('Y') }} SwiftCart. All rights reserved.
                    </td>
                </tr>

            </table>

        </td>
    </tr>
</table>

</body>
</html>
